#!/usr/bin/env python

import sys

header_fname = sys.argv[1]
output_fname = sys.argv[2]

header = '''
const char *
wdns_rrclass_to_str(uint16_t rrclass)
{
	switch (rrclass) {
'''

footer = '''	}

	return (NULL);
}
'''

w = open(output_fname, 'w')

w.write(header)

for line in open(header_fname):
    if 'WDNS_CLASS_' in line:
        wdns_class = line.split()[1]
        rrclass = wdns_class.rsplit('_', 1)[1]
        w.write('\tcase %s: return ("%s");\n' % (wdns_class, rrclass))

w.write(footer)
w.close()
